### ISSUE TITLE
Is there a demo for menu or toolbar layout?

### ISSUE THREAD

**Issue by bitbegin** [saphirion/r3-gui#3]
RebGUI can use menu and toolbar layout to complete the complex GUI design. How can r3-gui achieve this goal?

**Comment by Robert-M-Muench** [comment]
> RebGUI can use menu and toolbar layout to complete the complex GUI design. How can r3-gui  
> achieve this goal?

Hi, please refer to the available documentation, there are some examples. Menus and toolbars are possible in R3-GUI. Further please get connected to the AltMe world „Rebol4“ where you will get a lot of help by the community. Within this world there exists a group for R3-GUI.

Best regards. Robert M. Münch
